name: Update Project Dependencies
description: This workflow updates the project dependencies in the package-lock.json file and mix.lock files, committing changes if any updates are made.

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: 

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: npm update

      - name: Save updated lockfile
        run: cp package-lock.json $GITHUB_WORKSPACE/frontend-package-lock.json

  update-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with: 
          elixir-version: '1.17.3'
          otp-version: '27.0'
          
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            backend/deps
            backend/_build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
          
      - name: Install Hex and Rebar
        run: |
          mix local.hex --force
          mix local.rebar --force
          
      - name: Install dependencies
        run: mix deps.get
        
      - name: Update dependencies
        run: mix deps.update --all

      - name: Save updated lockfile
        run: cp mix.lock $GITHUB_WORKSPACE/backend-mix.lock

  commit-updated-deps:
    runs-on: ubuntu-latest
    needs: [update-frontend, update-backend]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore updated lockfiles
        run: |
          cp $GITHUB_WORKSPACE/frontend-package-lock.json frontend/package-lock.json || true
          cp $GITHUB_WORKSPACE/backend-mix.lock backend/mix.lock || true

      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push updated dependencies
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add frontend/package-lock.json backend/mix.lock
          git commit -m "chore: Update project dependencies"
          git push
